### ISSUE TITLE
Why not take a NamedTuple type object?

### ISSUE THREAD

**Issue by terrdavis** [erberlin/namedzip#1]
This would allow re-use of namedtuples elsewhere, simplify this package, and allow users to choose the new NamedTuple syntax:
```python
class MyTuple(NamedTuple):
    field1: str
    field2: int
```

**Comment by erberlin** [comment]
Thanks for your input @terrdavis. Could you please expand a little on your implementation idea?

**Comment by terrdavis** [comment]
The changes could be very simple:
```python
namedzip[_longest](*iterables, named_tuple):
    named_tuple = namedtuple(typename, field_names)  # remove this line
    # the rest is unchanged
```

Or, if you don't want to break the api:
```python
namedzip[_longest](*iterables, named_tuple=None, typename=None, field_names=None, **kwargs):
    named_tuple = named_tuple or namedtuple(typename, field_names, **kwargs)
    # the rest is unchanged
```

**Comment by erberlin** [comment]
For whatever reason I though you were referring to the `typing.NamedTuple` class when I first read the title, but I see what you're saying and I think it's a good idea.

It'll require some tweaking of the defaults implementation and stuff, but I'll take a stab at a non-breaking version when I get a chance.

**Comment by erberlin** [comment]
@terrdavis any thoughts on #2 ?

**Comment by terrdavis** [comment]
After playing around with it, I came up with some suggestions, and found two bugs:
Bugs: 
1. namedzip_longest does not respect defaults defined by a `NamedTuple` subclass. Cause of this appears to be `_fields_defaults` vs `_field_defaults` confusion.

```python
sys.version
'3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]'

nt = namedtuple('nt', 'x y', defaults=(0, 1))
class NT(NamedTuple):
     x: int = 0
     y: int = 1

print(*namedzip_longest((1,2,3,4,5),(4,5,6,7), named_tuple=nt))
# nt(x=1, y=4) nt(x=2, y=5) nt(x=3, y=6) nt(x=4, y=7) nt(x=5, y=1)

print(*namedzip_longest((1,2,3,4,5),(4,5,6,7), named_tuple=NT))
# NT(x=1, y=4) NT(x=2, y=5) NT(x=3, y=6) NT(x=4, y=7) NT(x=5, y=None)

vars(nt)
mappingproxy({'__doc__': 'nt(x, y)',
              '__slots__': (),
              '_fields': ('x', 'y'),
              '_fields_defaults': {'x': 0, 'y': 1},
              '__new__': <staticmethod at 0x6089710>,
              '_make': <classmethod at 0x1a961c50>,
              '_replace': <function collections.nt._replace(_self, **kwds)>,
              '__repr__': <function collections.nt.__repr__(self)>,
              '_asdict': <function collections.nt._asdict(self)>,
              '__getnewargs__': <function collections.nt.__getnewargs__(self)>,
              'x': <property at 0x1a9047c8>,
              'y': <property at 0x1a9042c8>,
              '__module__': '__main__'})

vars(NT)
mappingproxy({'__doc__': 'NT(x, y)',
              '__slots__': (),
              '_fields': ('x', 'y'),
              '_fields_defaults': {},
              '__new__': <staticmethod at 0x6201160>,
              '_make': <classmethod at 0x62010f0>,
              '_replace': <function collections.NT._replace(_self, **kwds)>,
              '__repr__': <function collections.NT.__repr__(self)>,
              '_asdict': <function collections.NT._asdict(self)>,
              '__getnewargs__': <function collections.NT.__getnewargs__(self)>,
              'x': <property at 0x1a8f97c8>,
              'y': <property at 0x1a2fa7c8>,
              '__module__': '__main__',
              '__annotations__': OrderedDict([('x', ForwardRef('int')),
                           ('y', ForwardRef('int'))]),
              '_field_types': OrderedDict([('x', ForwardRef('int')),
                           ('y', ForwardRef('int'))]),
              '_field_defaults': {'x': 0, 'y': 1}})
```
Solution: `getattr(nt, "_field_defaults", None) or getattr("_fields_default", None)` (Use `or` instead of nesting in case `_field_defaults` exists, but is an empty dict and `_fields_default` is filled instead.)

2. Any `None` values in iterables will get overridden by `defaults`.
```python
print(*namedzip_longest((1,2,3,4,5),(4,5,6,7,None), named_tuple=nt))
nt(x=1, y=4) nt(x=2, y=5) nt(x=3, y=6) nt(x=4, y=7) nt(x=5, y=1)
```
Solution: use a sentinel `object()` as the `fillvalue` for `zip_longest`, and replace those with the user-supplied `fillvalue` as needed.

Changes:

1. Split the api, so the zip and the zip factories are separate, with a `DeprecationWarning` for the old behavior:
    * `namedzip(*iterables, named_tuple=None, typename=None, field_names=None, **kwargs)`
    * `namedzipper(named_tuple=None, typename=None, field_names=None, **kwargs)`
    * `namedzip_longest(*iterables, named_tuple=None, typename=None, field_names=None, **kwargs)`
    * `namedzipper_longest(named_tuple=None, typename=None, field_names=None, **kwargs)`
OR  
2. Enable my laziness; leave the same signatures, but allow this usage: 
    ```python
    class Point(NamedTuple):
        x: float
        y: float

    zippoints = namedzip(Point)
    ```
3.  Break the API (preferred):
     * New API:
        ```python
        namedzip(named_tuple, *iterables)
        namedzip_longest(named_tuple, *iterables, fillvalue=None)
        # Return a generator or the new zip callable
        ```  
    * Much simpler.
    * You would only need to handle the edge case where there are `_field_defaults`.
    * You could use a deprecation decorator as described [here](https://dev.to/kchawla_pi/using-a-decorators-to-solve-my-task-the-thinking--the-process-49f0).

**Comment by erberlin** [comment]
Thanks for the feedback. I agree that your breaking suggestion is cleaner and here's what I came up with: #3 It now accepts both kinds of named tuples with defaults specified, and still allows for defaults to be specified in `namedzip_longest` as well.

**Comment by terrdavis** [comment]
That's awesome! I'll check it out today!

**Comment by terrdavis** [comment]
My only request is that you include a `namedtuple` from collections and maybe `NamedTuple` from typing to save users the extra import. I'm not sure about the second one due to `import typing` being very slow.  
I would also bump the version to 2.0 due to the API break.

**Comment by erberlin** [comment]
I'm updating the documentation now and plan to increment the minor version until removing backwards compatibility.  I'm not sure if I understand you correctly, but how would I make `namedtuple` available in the caller's namespace after only importing `namedzip` or `namedzip_longest`? Or do you mean allowing `from namedzip import namedtuple, namedzip` ?

**Comment by terrdavis** [comment]
Yes, that's what I meant.

```python
# namedzip.__init__.py
from .namedzip import namedzip, namedzip_longest
from collections import namedtuple
from typing import NamedTuple  # maybe
__all__ = 'namedzip', 'namedzip_longest', 'namedtuple', 'NamedTuple'  # maybe NamedTuple
__version__ = '2.0'
```

**Comment by erberlin** [comment]
Gotcha; I included `namedtuple` for now. Thanks for all the feedback!
